baseURL = "https://cryptocodes.ca/"
languageCode = "en-us"
title = "CryptoCodes.ca"
theme = "gruvhugo"
paginate = "10" # Number of posts per page

#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------


# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "crypto, codes, signup, free, Canadian, referral, rewards"
  headerTitle = "CryptoCodes.ca"
  copyright = "© <- This is definitely not copyrighted. Re-use & multiply!"
  name = "CryptoCodes.ca"
  img = "img/trees.jpeg"
  img_title = "Trees may love crypto. But you have to talk to them and hear their stories first."
  icon = "img/logo.png"
  quote = "I prefer trees over crypto. But crypto is here. Here are your codes."
  description= "I'm in Ontario, Canada. I do tech. I care about security and good in the world. I'm reluctantly learning crypto by doing crypto. I did some research, picked some decent exchanges and got some cash money. So here are the legit, \"secure\" exchanges I signed up for and the best reward freebies for the least investment. I'll keep this up to date, but if I get waay too busy looking at trees and they go stale, they can be found easily enough on the internetz. I promise to do only good with the millions I make from your good fortune. "
  licenseUrl = ""

 # Social icons
#  [[params.social]]
#    name = "gitlab"
#    url  = "https://gitlab.com/avron/gruvhugo"
#
#  [[params.social]]
#    name = "email"
#    url  = "mailto:mail@mail.com"
#
#  [[params.social]]
#    name = "gpg"
#    url  = "https://keys.openpgp.org/"
#
#  [[params.social]]
#    name = "twitter"
#    url  = "https://twitter.com/"
#
#  [[params.social]]
#    name = "github"
#    url  = "https://github.com/"
#
#  [[params.social]]
#    name = "linkedin"
#    url  = "https://www.linkedin.com/"

[params.style]
  # add path to custom CSS files here
  custom_css = []
  # add path to custom SCSS files here
  custom_scss = []

[menu]

  [[menu.main]]
    identifier = "codes"
    name       = "\"Free Money\" Codes"
    url        = "codes"

  [[menu.main]]
    identifier = "reading"
    name       = "Crypto the Good"
    url        = "reading"


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
